services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bank_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - elk
    restart: unless-stopped

#  myApp:
#    container_name: spring-boot
#    image: spring/bootcamp
#    ports:
#      - "8080:8087"
#    networks:
#      - elasticsearch
#    depends_on:
#      - postgres

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - bootstrap.system_call_filter=false
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.15.2
    ports:
      - "5300:5300"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge

volumes:
  postgres:
    driver: local
  data01:
    driver: local
