name: Listen-Dev Check

on:
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: listendev/action@v0.10
        with:
          jwt: ${{ secrets.LSTN_API_KEY }}
          ci: only
